export const IpcChannels = {
  app: {
    getVersion: 'app:getVersion',
  },
  settings: {
    getTheme: 'settings:getTheme',
    setTheme: 'settings:setTheme',
    getAccent: 'settings:getAccent',
    setAccent: 'settings:setAccent',
    getLocale: 'settings:getLocale',
    setLocale: 'settings:setLocale',
    getSnapshot: 'settings:getSnapshot',
    getDesktopWidget: 'settings:getDesktopWidget',
    setDesktopWidget: 'settings:setDesktopWidget',
    desktopWidgetUpdated: 'settings:desktopWidgetUpdated',
    pickDialBackground: 'settings:pickDialBackground',
    clearDialBackground: 'settings:clearDialBackground',
    selectDialBackground: 'settings:selectDialBackground',
    deleteDialBackground: 'settings:deleteDialBackground',
    setLaunchBehavior: 'settings:setLaunchBehavior',
    setNotifications: 'settings:setNotifications',
    setFortuneSettings: 'settings:setFortuneSettings',
    setStocksSettings: 'settings:setStocksSettings',
  },
  window: {
    openCalendar: 'window:openCalendar',
    closeCalendar: 'window:closeCalendar',
    showMain: 'window:showMain',
    dialDragStart: 'window:dialDragStart',
    dialDragEnd: 'window:dialDragEnd',
  },
  calendar: {
    getMode: 'calendar:getMode',
    setMode: 'calendar:setMode',
  },
  fortune: {
    getProfile: 'fortune:getProfile',
    saveProfile: 'fortune:saveProfile',
    clearProfile: 'fortune:clearProfile',
    generateAiAnalysis: 'fortune:generateAiAnalysis',
    testAiConnection: 'fortune:testAiConnection',
  },
  workbench: {
    chat: 'workbench:chat',
    chatStream: 'workbench:chatStream',
    chatStreamEvent: 'workbench:chatStreamEvent',
    cancelStream: 'workbench:cancelStream',
    resolveToolApproval: 'workbench:resolveToolApproval',
  },
  harness: {
    getStore: 'harness:getStore',
    migrateLocal: 'harness:migrateLocal',
    listSessions: 'harness:listSessions',
    createSession: 'harness:createSession',
    renameSession: 'harness:renameSession',
    deleteSession: 'harness:deleteSession',
    setActiveSession: 'harness:setActiveSession',
    listEvents: 'harness:listEvents',
    listMessages: 'harness:listMessages',
    appendUserMessage: 'harness:appendUserMessage',
    appendSystemMessage: 'harness:appendSystemMessage',
    forkSession: 'harness:forkSession',
    listGoals: 'harness:listGoals',
    setGoal: 'harness:setGoal',
    reloadPlugins: 'harness:reloadPlugins',
    listPlugins: 'harness:listPlugins',
    getSandboxRoot: 'harness:getSandboxRoot',
    setSandboxRoot: 'harness:setSandboxRoot',
    pickSandboxRoot: 'harness:pickSandboxRoot',
    getPluginsDir: 'harness:getPluginsDir',
    getDiagnostics: 'harness:getDiagnostics',
    listPluginCatalog: 'harness:listPluginCatalog',
    installPlugin: 'harness:installPlugin',
    pickInstallPlugin: 'harness:pickInstallPlugin',
    openPluginsDir: 'harness:openPluginsDir',
    ptyCreate: 'harness:ptyCreate',
    ptyWrite: 'harness:ptyWrite',
    ptyResize: 'harness:ptyResize',
    ptyKill: 'harness:ptyKill',
    ptyEvent: 'harness:ptyEvent',
    getCordisStack: 'harness:getCordisStack',
    reloadCordisStack: 'harness:reloadCordisStack',
    openCordisRoot: 'harness:openCordisRoot',
    getSandboxBackend: 'harness:getSandboxBackend',
    lspDefinition: 'harness:lspDefinition',
    lspCompletion: 'harness:lspCompletion',
    getDshWebUrl: 'harness:getDshWebUrl',
    setDshWebUrl: 'harness:setDshWebUrl',
    listCordisProfiles: 'harness:listCordisProfiles',
    listCordisBundles: 'harness:listCordisBundles',
    saveCordisSettings: 'harness:saveCordisSettings',
    createCordisProfile: 'harness:createCordisProfile',
    createCordisBundle: 'harness:createCordisBundle',
    getEmbeddedDshWebPreferred: 'harness:getEmbeddedDshWebPreferred',
    setEmbeddedDshWebPreferred: 'harness:setEmbeddedDshWebPreferred',
  },
  knowledge: {
    listDocuments: 'knowledge:listDocuments',
    ingestText: 'knowledge:ingestText',
    ingestFile: 'knowledge:ingestFile',
    deleteDocument: 'knowledge:deleteDocument',
    getDocumentFile: 'knowledge:getDocumentFile',
    search: 'knowledge:search',
    listCollections: 'knowledge:listCollections',
    createCollection: 'knowledge:createCollection',
    renameCollection: 'knowledge:renameCollection',
    deleteCollection: 'knowledge:deleteCollection',
    getSettings: 'knowledge:getSettings',
    setSettings: 'knowledge:setSettings',
    stats: 'knowledge:stats',
    reembedDocument: 'knowledge:reembedDocument',
    reembedCollection: 'knowledge:reembedCollection',
  },
  image: {
    generate: 'image:generate',
  },
  imageTools: {
    getSettings: 'imageTools:getSettings',
    setSettings: 'imageTools:setSettings',
    listModels: 'imageTools:listModels',
    installModel: 'imageTools:installModel',
    importModel: 'imageTools:importModel',
    uninstallModel: 'imageTools:uninstallModel',
    openModelsDir: 'imageTools:openModelsDir',
    pickModelsRoot: 'imageTools:pickModelsRoot',
    installProgress: 'imageTools:installProgress',
    runSmart: 'imageTools:runSmart',
    saveImage: 'imageTools:saveImage',
    readModelWeight: 'imageTools:readModelWeight',
    getModelPublicPath: 'imageTools:getModelPublicPath',
    upsertCustomEngine: 'imageTools:upsertCustomEngine',
    removeCustomEngine: 'imageTools:removeCustomEngine',
    pickCustomOnnx: 'imageTools:pickCustomOnnx',
  },
  debug: {
    getActivity: 'debug:getActivity',
    appendActivity: 'debug:appendActivity',
    clearActivity: 'debug:clearActivity',
    openMainLog: 'debug:openMainLog',
    readMainLogTail: 'debug:readMainLogTail',
    activityAppended: 'debug:activityAppended',
  },
  media: {
    transcribe: 'media:transcribe',
    generateVideo: 'media:generateVideo',
    generateMusic: 'media:generateMusic',
    pickAudioFile: 'media:pickAudioFile',
    getCapabilities: 'media:getCapabilities',
  },
  tools: {
    extractDocument: 'tools:extractDocument',
    saveTextFile: 'tools:saveTextFile',
    saveMediaFile: 'tools:saveMediaFile',
    mergePdfs: 'tools:mergePdfs',
    splitPdf: 'tools:splitPdf',
    exportPdf: 'tools:exportPdf',
    exportDocx: 'tools:exportDocx',
    compressPdf: 'tools:compressPdf',
    encryptPdf: 'tools:encryptPdf',
    checkLibreOffice: 'tools:checkLibreOffice',
    convertLibreOffice: 'tools:convertLibreOffice',
    pickLibreOffice: 'tools:pickLibreOffice',
    clearLibreOffice: 'tools:clearLibreOffice',
    openLibreOfficeDownload: 'tools:openLibreOfficeDownload',
  },
  videoTools: {
    checkFfmpeg: 'videoTools:checkFfmpeg',
    pickVideo: 'videoTools:pickVideo',
    importVideo: 'videoTools:importVideo',
    probe: 'videoTools:probe',
    process: 'videoTools:process',
    concat: 'videoTools:concat',
    multiTrack: 'videoTools:multiTrack',
    pickImage: 'videoTools:pickImage',
    pickSubtitle: 'videoTools:pickSubtitle',
    progress: 'videoTools:progress',
  },
  audioTools: {
    pickAudio: 'audioTools:pickAudio',
    importAudio: 'audioTools:importAudio',
    process: 'audioTools:process',
    concat: 'audioTools:concat',
    progress: 'audioTools:progress',
  },
  mcp: {
    getSettings: 'mcp:getSettings',
    setSettings: 'mcp:setSettings',
    listTools: 'mcp:listTools',
    getStatus: 'mcp:getStatus',
    refreshStatus: 'mcp:refreshStatus',
  },
  stocks: {
    getWatchlist: 'stocks:getWatchlist',
    addWatchlistItem: 'stocks:addWatchlistItem',
    removeWatchlistItem: 'stocks:removeWatchlistItem',
    getScannerPool: 'stocks:getScannerPool',
    addScannerPoolItem: 'stocks:addScannerPoolItem',
    removeScannerPoolItem: 'stocks:removeScannerPoolItem',
    importWatchlistCsv: 'stocks:importWatchlistCsv',
    exportWatchlistCsv: 'stocks:exportWatchlistCsv',
    importScannerCsv: 'stocks:importScannerCsv',
    exportScannerCsv: 'stocks:exportScannerCsv',
    generateReport: 'stocks:generateReport',
    getLatestReport: 'stocks:getLatestReport',
    listReports: 'stocks:listReports',
    getReportByDate: 'stocks:getReportByDate',
    getQuote: 'stocks:getQuote',
    refreshScanner: 'stocks:refreshScanner',
  },
  skills: {
    list: 'skills:list',
    catalogs: 'skills:catalogs',
    installGithub: 'skills:installGithub',
    installMarkdown: 'skills:installMarkdown',
    uninstall: 'skills:uninstall',
  },
  backup: {
    export: 'backup:export',
    import: 'backup:import',
  },
  system: {
    getLaunchAtLogin: 'system:getLaunchAtLogin',
    setLaunchAtLogin: 'system:setLaunchAtLogin',
  },
} as const

export type ThemeMode = 'light' | 'dark' | 'system'
export type AppLocale = 'zh-CN' | 'en-US'
