export const IpcChannels = {
  app: {
    getVersion: 'app:getVersion',
  },
  settings: {
    getTheme: 'settings:getTheme',
    setTheme: 'settings:setTheme',
    getLocale: 'settings:getLocale',
    setLocale: 'settings:setLocale',
    getSnapshot: 'settings:getSnapshot',
    getDesktopWidget: 'settings:getDesktopWidget',
    setDesktopWidget: 'settings:setDesktopWidget',
    desktopWidgetUpdated: 'settings:desktopWidgetUpdated',
    pickDialBackground: 'settings:pickDialBackground',
    clearDialBackground: 'settings:clearDialBackground',
    selectDialBackground: 'settings:selectDialBackground',
    deleteDialBackground: 'settings:deleteDialBackground',
    setLaunchBehavior: 'settings:setLaunchBehavior',
    setNotifications: 'settings:setNotifications',
    setFortuneSettings: 'settings:setFortuneSettings',
    setStocksSettings: 'settings:setStocksSettings',
  },
  window: {
    openCalendar: 'window:openCalendar',
    closeCalendar: 'window:closeCalendar',
    showMain: 'window:showMain',
    dialDragStart: 'window:dialDragStart',
    dialDragEnd: 'window:dialDragEnd',
  },
  calendar: {
    getMode: 'calendar:getMode',
    setMode: 'calendar:setMode',
  },
  fortune: {
    getProfile: 'fortune:getProfile',
    saveProfile: 'fortune:saveProfile',
    clearProfile: 'fortune:clearProfile',
    generateAiAnalysis: 'fortune:generateAiAnalysis',
    testAiConnection: 'fortune:testAiConnection',
  },
  workbench: {
    chat: 'workbench:chat',
    chatStream: 'workbench:chatStream',
    chatStreamEvent: 'workbench:chatStreamEvent',
  },
  knowledge: {
    listDocuments: 'knowledge:listDocuments',
    ingestText: 'knowledge:ingestText',
    ingestFile: 'knowledge:ingestFile',
    deleteDocument: 'knowledge:deleteDocument',
    getDocumentFile: 'knowledge:getDocumentFile',
    search: 'knowledge:search',
    listCollections: 'knowledge:listCollections',
    createCollection: 'knowledge:createCollection',
    renameCollection: 'knowledge:renameCollection',
    deleteCollection: 'knowledge:deleteCollection',
    getSettings: 'knowledge:getSettings',
    setSettings: 'knowledge:setSettings',
    stats: 'knowledge:stats',
    reembedDocument: 'knowledge:reembedDocument',
    reembedCollection: 'knowledge:reembedCollection',
  },
  image: {
    generate: 'image:generate',
  },
  mcp: {
    getSettings: 'mcp:getSettings',
    setSettings: 'mcp:setSettings',
    listTools: 'mcp:listTools',
  },
  stocks: {
    getWatchlist: 'stocks:getWatchlist',
    addWatchlistItem: 'stocks:addWatchlistItem',
    removeWatchlistItem: 'stocks:removeWatchlistItem',
    getScannerPool: 'stocks:getScannerPool',
    addScannerPoolItem: 'stocks:addScannerPoolItem',
    removeScannerPoolItem: 'stocks:removeScannerPoolItem',
    importWatchlistCsv: 'stocks:importWatchlistCsv',
    exportWatchlistCsv: 'stocks:exportWatchlistCsv',
    importScannerCsv: 'stocks:importScannerCsv',
    exportScannerCsv: 'stocks:exportScannerCsv',
    generateReport: 'stocks:generateReport',
    getLatestReport: 'stocks:getLatestReport',
    listReports: 'stocks:listReports',
    getReportByDate: 'stocks:getReportByDate',
    getQuote: 'stocks:getQuote',
    refreshScanner: 'stocks:refreshScanner',
  },
  skills: {
    list: 'skills:list',
    catalogs: 'skills:catalogs',
    installGithub: 'skills:installGithub',
    installMarkdown: 'skills:installMarkdown',
    uninstall: 'skills:uninstall',
  },
  backup: {
    export: 'backup:export',
    import: 'backup:import',
  },
  system: {
    getLaunchAtLogin: 'system:getLaunchAtLogin',
    setLaunchAtLogin: 'system:setLaunchAtLogin',
  },
} as const

export type ThemeMode = 'light' | 'dark' | 'system'
export type AppLocale = 'zh-CN' | 'en-US'
