import type { AiModelConfig } from '../aiModels'
import type { MediaProfileId } from './media'

/** Calendar system used for birth date input. */
export type BirthCalendar = 'solar' | 'lunar'

/** Traditional Chinese hour branches; `unknown` skips the hour pillar. */
export type BirthHourBranch =
  | 'unknown'
  | 'zi'
  | 'chou'
  | 'yin'
  | 'mao'
  | 'chen'
  | 'si'
  | 'wu'
  | 'wei'
  | 'shen'
  | 'you'
  | 'xu'
  | 'hai'

export const BIRTH_HOUR_BRANCHES: BirthHourBranch[] = [
  'unknown',
  'zi',
  'chou',
  'yin',
  'mao',
  'chen',
  'si',
  'wu',
  'wei',
  'shen',
  'you',
  'xu',
  'hai',
]

/** Hexagram mapping school — all locally reproducible. */
export type HexagramSchool = 'daymaster' | 'meihua' | 'liuyao'

export const HEXAGRAM_SCHOOLS: HexagramSchool[] = ['daymaster', 'meihua', 'liuyao']

export interface FortuneAiProviderConfig {
  id: string
  name: string
  baseUrl: string
  apiFormat: 'openai' | 'anthropic'
  models: AiModelConfig[]
  apiKey: string
  /**
   * Media protocol profile for image/video/music.
   * `auto` suggests from Base URL; user may override in Settings.
   */
  mediaProfile?: MediaProfileId
  /** Optional dedicated models (fall back to chat model / adapter default). */
  imageModel?: string
  videoModel?: string
  musicModel?: string
}

export interface FortuneSettings {
  /** Recommended default: daymaster (日主 + 当日干支映射). */
  hexagramSchool: HexagramSchool
  /** Optional AI copy polish; default off. */
  aiPolish: boolean
  /** OpenAI-compatible base URL, e.g. https://api.openai.com/v1 */
  aiBaseUrl: string
  /** Provider display name. */
  aiProviderName: string
  /** API protocol format. */
  aiApiFormat: 'openai' | 'anthropic'
  /** Available model ids for quick selection. */
  aiModels: string[]
  /** OpenAI-compatible model id. */
  aiModel: string
  /** API key for online AI analysis. */
  aiApiKey: string
  /** Multi-provider configurations. */
  aiProviders: FortuneAiProviderConfig[]
  /** Active provider id in aiProviders. */
  aiActiveProviderId: string
}

export const DEFAULT_FORTUNE_SETTINGS: FortuneSettings = {
  hexagramSchool: 'daymaster',
  aiPolish: false,
  aiBaseUrl: 'https://api.openai.com/v1',
  aiProviderName: 'OpenAI',
  aiApiFormat: 'openai',
  aiModels: [],
  aiModel: '',
  aiApiKey: '',
  aiProviders: [
    {
      id: 'default-openai',
      name: 'OpenAI',
      baseUrl: 'https://api.openai.com/v1',
      apiFormat: 'openai',
      models: [],
      apiKey: '',
      mediaProfile: 'auto',
    },
  ],
  aiActiveProviderId: 'default-openai',
}

export type FortuneInputMode = 'birthDate' | 'bazi'

export interface BirthProfile {
  id: string
  name: string
  inputMode: FortuneInputMode
  /** YYYY-MM-DD when inputMode is birthDate */
  birthDate?: string
  birthCalendar?: BirthCalendar
  hourBranch?: BirthHourBranch
  /** Four pillars when inputMode is bazi, e.g. 甲子 */
  yearPillar?: string
  monthPillar?: string
  dayPillar?: string
  hourPillar?: string
  updatedAt: string
}

export interface BaZiSnapshot {
  year: string
  month: string
  day: string
  hour: string | null
  dayMaster: string
  hourKnown: boolean
  animal: string
  yinYang: 'yang' | 'yin'
  element: string
}

export type FortuneLevel = 'excellent' | 'good' | 'fair' | 'caution'

export type HexagramTendency = 'favorable' | 'neutral' | 'caution'

export interface HexagramInfo {
  id: number
  name: string
  nameFull: string
  nameEn: string
  tendency: HexagramTendency
}

export type FortuneAspectKey = 'career' | 'wealth' | 'relationship' | 'health' | 'mood'

export interface FortuneAspect {
  score: number
  level: FortuneLevel
  blurb: string
}

export interface DailyFortune {
  date: string
  profileId: string
  bazi: BaZiSnapshot
  hexagram: HexagramInfo & {
    summary: string
    advice: string
  }
  overall: {
    score: number
    level: FortuneLevel
    blurb: string
  }
  aspects: Record<FortuneAspectKey, FortuneAspect>
  lucky: {
    colors: string[]
    directions: string[]
    numbers: number[]
  }
  disclaimer: string
  /**
   * Optional “AI analysis”/copy supplement.
   * It can be generated by local fallback logic or an online AI provider.
   */
  aiAnalysis?: string
  source: {
    engine: string
    aiPolished: boolean
  }
}

export interface FortuneAiRequest {
  fortune: DailyFortune
  locale: string
}

export interface FortuneAiResponse {
  ok: boolean
  text?: string
  error?: string
}

export interface FortuneAiConnectionTestInput {
  provider: FortuneAiProviderConfig
  model: string
}

export interface FortuneAiConnectionTestResponse {
  ok: boolean
  message: string
}
