import type { HexagramInfo } from '@shared'

/** King Wen sequence — local fortune engine v1. */
export const HEXAGRAMS: HexagramInfo[] = [
  { id: 1, name: '乾', nameFull: '乾为天', nameEn: 'The Creative', tendency: 'favorable' },
  { id: 2, name: '坤', nameFull: '坤为地', nameEn: 'The Receptive', tendency: 'neutral' },
  { id: 3, name: '屯', nameFull: '水雷屯', nameEn: 'Difficulty at the Beginning', tendency: 'caution' },
  { id: 4, name: '蒙', nameFull: '山水蒙', nameEn: 'Youthful Folly', tendency: 'caution' },
  { id: 5, name: '需', nameFull: '水天需', nameEn: 'Waiting', tendency: 'neutral' },
  { id: 6, name: '讼', nameFull: '天水讼', nameEn: 'Conflict', tendency: 'caution' },
  { id: 7, name: '师', nameFull: '地水师', nameEn: 'The Army', tendency: 'neutral' },
  { id: 8, name: '比', nameFull: '水地比', nameEn: 'Union', tendency: 'favorable' },
  { id: 9, name: '小畜', nameFull: '风天小畜', nameEn: 'Small Taming', tendency: 'neutral' },
  { id: 10, name: '履', nameFull: '天泽履', nameEn: 'Treading', tendency: 'caution' },
  { id: 11, name: '泰', nameFull: '地天泰', nameEn: 'Peace', tendency: 'favorable' },
  { id: 12, name: '否', nameFull: '天地否', nameEn: 'Standstill', tendency: 'caution' },
  { id: 13, name: '同人', nameFull: '天火同人', nameEn: 'Fellowship', tendency: 'favorable' },
  { id: 14, name: '大有', nameFull: '火天大有', nameEn: 'Great Possession', tendency: 'favorable' },
  { id: 15, name: '谦', nameFull: '地山谦', nameEn: 'Modesty', tendency: 'favorable' },
  { id: 16, name: '豫', nameFull: '雷地豫', nameEn: 'Enthusiasm', tendency: 'favorable' },
  { id: 17, name: '随', nameFull: '泽雷随', nameEn: 'Following', tendency: 'neutral' },
  { id: 18, name: '蛊', nameFull: '山风蛊', nameEn: 'Work on the Decayed', tendency: 'caution' },
  { id: 19, name: '临', nameFull: '地泽临', nameEn: 'Approach', tendency: 'favorable' },
  { id: 20, name: '观', nameFull: '风地观', nameEn: 'Contemplation', tendency: 'neutral' },
  { id: 21, name: '噬嗑', nameFull: '火雷噬嗑', nameEn: 'Biting Through', tendency: 'neutral' },
  { id: 22, name: '贲', nameFull: '山火贲', nameEn: 'Grace', tendency: 'favorable' },
  { id: 23, name: '剥', nameFull: '山地剥', nameEn: 'Splitting Apart', tendency: 'caution' },
  { id: 24, name: '复', nameFull: '地雷复', nameEn: 'Return', tendency: 'favorable' },
  { id: 25, name: '无妄', nameFull: '天雷无妄', nameEn: 'Innocence', tendency: 'neutral' },
  { id: 26, name: '大畜', nameFull: '山天大畜', nameEn: 'Great Taming', tendency: 'favorable' },
  { id: 27, name: '颐', nameFull: '山雷颐', nameEn: 'Nourishment', tendency: 'neutral' },
  { id: 28, name: '大过', nameFull: '泽风大过', nameEn: 'Great Exceeding', tendency: 'caution' },
  { id: 29, name: '坎', nameFull: '坎为水', nameEn: 'The Abysmal', tendency: 'caution' },
  { id: 30, name: '离', nameFull: '离为火', nameEn: 'The Clinging', tendency: 'favorable' },
  { id: 31, name: '咸', nameFull: '泽山咸', nameEn: 'Influence', tendency: 'favorable' },
  { id: 32, name: '恒', nameFull: '雷风恒', nameEn: 'Duration', tendency: 'neutral' },
  { id: 33, name: '遁', nameFull: '天山遁', nameEn: 'Retreat', tendency: 'caution' },
  { id: 34, name: '大壮', nameFull: '雷天大壮', nameEn: 'Great Power', tendency: 'favorable' },
  { id: 35, name: '晋', nameFull: '火地晋', nameEn: 'Progress', tendency: 'favorable' },
  { id: 36, name: '明夷', nameFull: '地火明夷', nameEn: 'Darkening of the Light', tendency: 'caution' },
  { id: 37, name: '家人', nameFull: '风火家人', nameEn: 'The Family', tendency: 'favorable' },
  { id: 38, name: '睽', nameFull: '火泽睽', nameEn: 'Opposition', tendency: 'caution' },
  { id: 39, name: '蹇', nameFull: '水山蹇', nameEn: 'Obstruction', tendency: 'caution' },
  { id: 40, name: '解', nameFull: '雷水解', nameEn: 'Deliverance', tendency: 'favorable' },
  { id: 41, name: '损', nameFull: '山泽损', nameEn: 'Decrease', tendency: 'caution' },
  { id: 42, name: '益', nameFull: '风雷益', nameEn: 'Increase', tendency: 'favorable' },
  { id: 43, name: '夬', nameFull: '泽天夬', nameEn: 'Breakthrough', tendency: 'favorable' },
  { id: 44, name: '姤', nameFull: '天风姤', nameEn: 'Coming to Meet', tendency: 'caution' },
  { id: 45, name: '萃', nameFull: '泽地萃', nameEn: 'Gathering', tendency: 'favorable' },
  { id: 46, name: '升', nameFull: '地风升', nameEn: 'Pushing Upward', tendency: 'favorable' },
  { id: 47, name: '困', nameFull: '泽水困', nameEn: 'Oppression', tendency: 'caution' },
  { id: 48, name: '井', nameFull: '水风井', nameEn: 'The Well', tendency: 'neutral' },
  { id: 49, name: '革', nameFull: '泽火革', nameEn: 'Revolution', tendency: 'neutral' },
  { id: 50, name: '鼎', nameFull: '火风鼎', nameEn: 'The Cauldron', tendency: 'favorable' },
  { id: 51, name: '震', nameFull: '震为雷', nameEn: 'The Arousing', tendency: 'neutral' },
  { id: 52, name: '艮', nameFull: '艮为山', nameEn: 'Keeping Still', tendency: 'neutral' },
  { id: 53, name: '渐', nameFull: '风山渐', nameEn: 'Development', tendency: 'favorable' },
  { id: 54, name: '归妹', nameFull: '雷泽归妹', nameEn: 'Marrying Maiden', tendency: 'caution' },
  { id: 55, name: '丰', nameFull: '雷火丰', nameEn: 'Abundance', tendency: 'favorable' },
  { id: 56, name: '旅', nameFull: '火山旅', nameEn: 'The Wanderer', tendency: 'neutral' },
  { id: 57, name: '巽', nameFull: '巽为风', nameEn: 'The Gentle', tendency: 'neutral' },
  { id: 58, name: '兑', nameFull: '兑为泽', nameEn: 'The Joyous', tendency: 'favorable' },
  { id: 59, name: '涣', nameFull: '风水涣', nameEn: 'Dispersion', tendency: 'neutral' },
  { id: 60, name: '节', nameFull: '水泽节', nameEn: 'Limitation', tendency: 'neutral' },
  { id: 61, name: '中孚', nameFull: '风泽中孚', nameEn: 'Inner Truth', tendency: 'favorable' },
  { id: 62, name: '小过', nameFull: '雷山小过', nameEn: 'Small Exceeding', tendency: 'caution' },
  { id: 63, name: '既济', nameFull: '水火既济', nameEn: 'After Completion', tendency: 'favorable' },
  { id: 64, name: '未济', nameFull: '火水未济', nameEn: 'Before Completion', tendency: 'caution' },
]

export function getHexagramById(id: number): HexagramInfo {
  const idx = ((id - 1) % 64 + 64) % 64
  return HEXAGRAMS[idx]!
}
