export type WorldCity = {
  id: string
  timezone: string
  flag: string
  cityZh: string
  cityEn: string
  countryZh: string
  countryEn: string
  featured?: boolean
}

export const WORLD_CITIES: WorldCity[] = [
  {
    id: "北京-Asia-Shanghai",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
    cityZh: "北京",
    cityEn: "Beijing",
    countryZh: "中国",
    countryEn: "China",
    featured: true,
  },
  {
    id: "纽约-America-New-York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    cityZh: "纽约",
    cityEn: "New York",
    countryZh: "美国",
    countryEn: "United States",
    featured: true,
  },
  {
    id: "伦敦-Europe-London",
    timezone: "Europe/London",
    flag: "🇬🇧",
    cityZh: "伦敦",
    cityEn: "London",
    countryZh: "英国",
    countryEn: "United Kingdom",
    featured: true,
  },
  {
    id: "东京-Asia-Tokyo",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
    cityZh: "东京",
    cityEn: "Tokyo",
    countryZh: "日本",
    countryEn: "Japan",
    featured: true,
  },
  {
    id: "巴黎-Europe-Paris",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
    cityZh: "巴黎",
    cityEn: "Paris",
    countryZh: "法国",
    countryEn: "France",
    featured: true,
  },
  {
    id: "悉尼-Australia-Sydney",
    timezone: "Australia/Sydney",
    flag: "🇦🇺",
    cityZh: "悉尼",
    cityEn: "Sydney",
    countryZh: "澳大利亚",
    countryEn: "Australia",
    featured: true,
  },
  {
    id: "迪拜-Asia-Dubai",
    timezone: "Asia/Dubai",
    flag: "🇦🇪",
    cityZh: "迪拜",
    cityEn: "Dubai",
    countryZh: "阿联酋",
    countryEn: "UAE",
    featured: true,
  },
  {
    id: "新加坡-Asia-Singapore",
    timezone: "Asia/Singapore",
    flag: "🇸🇬",
    cityZh: "新加坡",
    cityEn: "Singapore",
    countryZh: "新加坡",
    countryEn: "Singapore",
    featured: true,
  },
  {
    id: "上海-Asia-Shanghai",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
    cityZh: "上海",
    cityEn: "Shanghai",
    countryZh: "中国",
    countryEn: "China",
  },
  {
    id: "香港-Asia-Hong-Kong",
    timezone: "Asia/Hong_Kong",
    flag: "🇭🇰",
    cityZh: "香港",
    cityEn: "Hong Kong",
    countryZh: "中国",
    countryEn: "China",
  },
  {
    id: "台北-Asia-Taipei",
    timezone: "Asia/Taipei",
    flag: "🇹🇼",
    cityZh: "台北",
    cityEn: "Taipei",
    countryZh: "中国台湾",
    countryEn: "Taiwan",
  },
  {
    id: "澳门-Asia-Macau",
    timezone: "Asia/Macau",
    flag: "🇲🇴",
    cityZh: "澳门",
    cityEn: "Macau",
    countryZh: "中国",
    countryEn: "China",
  },
  {
    id: "大阪-Asia-Tokyo",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
    cityZh: "大阪",
    cityEn: "Osaka",
    countryZh: "日本",
    countryEn: "Japan",
  },
  {
    id: "首尔-Asia-Seoul",
    timezone: "Asia/Seoul",
    flag: "🇰🇷",
    cityZh: "首尔",
    cityEn: "Seoul",
    countryZh: "韩国",
    countryEn: "South Korea",
  },
  {
    id: "曼谷-Asia-Bangkok",
    timezone: "Asia/Bangkok",
    flag: "🇹🇭",
    cityZh: "曼谷",
    cityEn: "Bangkok",
    countryZh: "泰国",
    countryEn: "Thailand",
  },
  {
    id: "河内-Asia-Ho-Chi-Minh",
    timezone: "Asia/Ho_Chi_Minh",
    flag: "🇻🇳",
    cityZh: "河内",
    cityEn: "Hanoi",
    countryZh: "越南",
    countryEn: "Vietnam",
  },
  {
    id: "吉隆坡-Asia-Kuala-Lumpur",
    timezone: "Asia/Kuala_Lumpur",
    flag: "🇲🇾",
    cityZh: "吉隆坡",
    cityEn: "Kuala Lumpur",
    countryZh: "马来西亚",
    countryEn: "Malaysia",
  },
  {
    id: "马尼拉-Asia-Manila",
    timezone: "Asia/Manila",
    flag: "🇵🇭",
    cityZh: "马尼拉",
    cityEn: "Manila",
    countryZh: "菲律宾",
    countryEn: "Philippines",
  },
  {
    id: "雅加达-Asia-Jakarta",
    timezone: "Asia/Jakarta",
    flag: "🇮🇩",
    cityZh: "雅加达",
    cityEn: "Jakarta",
    countryZh: "印度尼西亚",
    countryEn: "Indonesia",
  },
  {
    id: "新德里-Asia-Kolkata",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
    cityZh: "新德里",
    cityEn: "New Delhi",
    countryZh: "印度",
    countryEn: "India",
  },
  {
    id: "孟买-Asia-Kolkata",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
    cityZh: "孟买",
    cityEn: "Mumbai",
    countryZh: "印度",
    countryEn: "India",
  },
  {
    id: "达卡-Asia-Dhaka",
    timezone: "Asia/Dhaka",
    flag: "🇧🇩",
    cityZh: "达卡",
    cityEn: "Dhaka",
    countryZh: "孟加拉国",
    countryEn: "Bangladesh",
  },
  {
    id: "加德满都-Asia-Kathmandu",
    timezone: "Asia/Kathmandu",
    flag: "🇳🇵",
    cityZh: "加德满都",
    cityEn: "Kathmandu",
    countryZh: "尼泊尔",
    countryEn: "Nepal",
  },
  {
    id: "伊斯兰堡-Asia-Karachi",
    timezone: "Asia/Karachi",
    flag: "🇵🇰",
    cityZh: "伊斯兰堡",
    cityEn: "Islamabad",
    countryZh: "巴基斯坦",
    countryEn: "Pakistan",
  },
  {
    id: "阿布扎比-Asia-Dubai",
    timezone: "Asia/Dubai",
    flag: "🇦🇪",
    cityZh: "阿布扎比",
    cityEn: "Abu Dhabi",
    countryZh: "阿联酋",
    countryEn: "UAE",
  },
  {
    id: "利雅得-Asia-Riyadh",
    timezone: "Asia/Riyadh",
    flag: "🇸🇦",
    cityZh: "利雅得",
    cityEn: "Riyadh",
    countryZh: "沙特阿拉伯",
    countryEn: "Saudi Arabia",
  },
  {
    id: "多哈-Asia-Qatar",
    timezone: "Asia/Qatar",
    flag: "🇶🇦",
    cityZh: "多哈",
    cityEn: "Doha",
    countryZh: "卡塔尔",
    countryEn: "Qatar",
  },
  {
    id: "特拉维夫-Asia-Jerusalem",
    timezone: "Asia/Jerusalem",
    flag: "🇮🇱",
    cityZh: "特拉维夫",
    cityEn: "Tel Aviv",
    countryZh: "以色列",
    countryEn: "Israel",
  },
  {
    id: "安卡拉-Europe-Istanbul",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
    cityZh: "安卡拉",
    cityEn: "Ankara",
    countryZh: "土耳其",
    countryEn: "Turkey",
  },
  {
    id: "伊斯坦布尔-Europe-Istanbul",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
    cityZh: "伊斯坦布尔",
    cityEn: "Istanbul",
    countryZh: "土耳其",
    countryEn: "Turkey",
  },
  {
    id: "德黑兰-Asia-Tehran",
    timezone: "Asia/Tehran",
    flag: "🇮🇷",
    cityZh: "德黑兰",
    cityEn: "Tehran",
    countryZh: "伊朗",
    countryEn: "Iran",
  },
  {
    id: "莫斯科-Europe-Moscow",
    timezone: "Europe/Moscow",
    flag: "🇷🇺",
    cityZh: "莫斯科",
    cityEn: "Moscow",
    countryZh: "俄罗斯",
    countryEn: "Russia",
  },
  {
    id: "圣彼得堡-Europe-Moscow",
    timezone: "Europe/Moscow",
    flag: "🇷🇺",
    cityZh: "圣彼得堡",
    cityEn: "Saint Petersburg",
    countryZh: "俄罗斯",
    countryEn: "Russia",
  },
  {
    id: "柏林-Europe-Berlin",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
    cityZh: "柏林",
    cityEn: "Berlin",
    countryZh: "德国",
    countryEn: "Germany",
  },
  {
    id: "法兰克福-Europe-Berlin",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
    cityZh: "法兰克福",
    cityEn: "Frankfurt",
    countryZh: "德国",
    countryEn: "Germany",
  },
  {
    id: "慕尼黑-Europe-Berlin",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
    cityZh: "慕尼黑",
    cityEn: "Munich",
    countryZh: "德国",
    countryEn: "Germany",
  },
  {
    id: "罗马-Europe-Rome",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
    cityZh: "罗马",
    cityEn: "Rome",
    countryZh: "意大利",
    countryEn: "Italy",
  },
  {
    id: "米兰-Europe-Rome",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
    cityZh: "米兰",
    cityEn: "Milan",
    countryZh: "意大利",
    countryEn: "Italy",
  },
  {
    id: "马德里-Europe-Madrid",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
    cityZh: "马德里",
    cityEn: "Madrid",
    countryZh: "西班牙",
    countryEn: "Spain",
  },
  {
    id: "巴塞罗那-Europe-Madrid",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
    cityZh: "巴塞罗那",
    cityEn: "Barcelona",
    countryZh: "西班牙",
    countryEn: "Spain",
  },
  {
    id: "阿姆斯特丹-Europe-Amsterdam",
    timezone: "Europe/Amsterdam",
    flag: "🇳🇱",
    cityZh: "阿姆斯特丹",
    cityEn: "Amsterdam",
    countryZh: "荷兰",
    countryEn: "Netherlands",
  },
  {
    id: "布鲁塞尔-Europe-Brussels",
    timezone: "Europe/Brussels",
    flag: "🇧🇪",
    cityZh: "布鲁塞尔",
    cityEn: "Brussels",
    countryZh: "比利时",
    countryEn: "Belgium",
  },
  {
    id: "维也纳-Europe-Vienna",
    timezone: "Europe/Vienna",
    flag: "🇦🇹",
    cityZh: "维也纳",
    cityEn: "Vienna",
    countryZh: "奥地利",
    countryEn: "Austria",
  },
  {
    id: "苏黎世-Europe-Zurich",
    timezone: "Europe/Zurich",
    flag: "🇨🇭",
    cityZh: "苏黎世",
    cityEn: "Zurich",
    countryZh: "瑞士",
    countryEn: "Switzerland",
  },
  {
    id: "日内瓦-Europe-Zurich",
    timezone: "Europe/Zurich",
    flag: "🇨🇭",
    cityZh: "日内瓦",
    cityEn: "Geneva",
    countryZh: "瑞士",
    countryEn: "Switzerland",
  },
  {
    id: "斯德哥尔摩-Europe-Stockholm",
    timezone: "Europe/Stockholm",
    flag: "🇸🇪",
    cityZh: "斯德哥尔摩",
    cityEn: "Stockholm",
    countryZh: "瑞典",
    countryEn: "Sweden",
  },
  {
    id: "哥本哈根-Europe-Copenhagen",
    timezone: "Europe/Copenhagen",
    flag: "🇩🇰",
    cityZh: "哥本哈根",
    cityEn: "Copenhagen",
    countryZh: "丹麦",
    countryEn: "Denmark",
  },
  {
    id: "奥斯陆-Europe-Oslo",
    timezone: "Europe/Oslo",
    flag: "🇳🇴",
    cityZh: "奥斯陆",
    cityEn: "Oslo",
    countryZh: "挪威",
    countryEn: "Norway",
  },
  {
    id: "赫尔辛基-Europe-Helsinki",
    timezone: "Europe/Helsinki",
    flag: "🇫🇮",
    cityZh: "赫尔辛基",
    cityEn: "Helsinki",
    countryZh: "芬兰",
    countryEn: "Finland",
  },
  {
    id: "华沙-Europe-Warsaw",
    timezone: "Europe/Warsaw",
    flag: "🇵🇱",
    cityZh: "华沙",
    cityEn: "Warsaw",
    countryZh: "波兰",
    countryEn: "Poland",
  },
  {
    id: "布拉格-Europe-Prague",
    timezone: "Europe/Prague",
    flag: "🇨🇿",
    cityZh: "布拉格",
    cityEn: "Prague",
    countryZh: "捷克",
    countryEn: "Czechia",
  },
  {
    id: "布达佩斯-Europe-Budapest",
    timezone: "Europe/Budapest",
    flag: "🇭🇺",
    cityZh: "布达佩斯",
    cityEn: "Budapest",
    countryZh: "匈牙利",
    countryEn: "Hungary",
  },
  {
    id: "雅典-Europe-Athens",
    timezone: "Europe/Athens",
    flag: "🇬🇷",
    cityZh: "雅典",
    cityEn: "Athens",
    countryZh: "希腊",
    countryEn: "Greece",
  },
  {
    id: "里斯本-Europe-Lisbon",
    timezone: "Europe/Lisbon",
    flag: "🇵🇹",
    cityZh: "里斯本",
    cityEn: "Lisbon",
    countryZh: "葡萄牙",
    countryEn: "Portugal",
  },
  {
    id: "都柏林-Europe-Dublin",
    timezone: "Europe/Dublin",
    flag: "🇮🇪",
    cityZh: "都柏林",
    cityEn: "Dublin",
    countryZh: "爱尔兰",
    countryEn: "Ireland",
  },
  {
    id: "华盛顿-America-New-York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    cityZh: "华盛顿",
    cityEn: "Washington",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "洛杉矶-America-Los-Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    cityZh: "洛杉矶",
    cityEn: "Los Angeles",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "旧金山-America-Los-Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    cityZh: "旧金山",
    cityEn: "San Francisco",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "芝加哥-America-Chicago",
    timezone: "America/Chicago",
    flag: "🇺🇸",
    cityZh: "芝加哥",
    cityEn: "Chicago",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "休斯顿-America-Chicago",
    timezone: "America/Chicago",
    flag: "🇺🇸",
    cityZh: "休斯顿",
    cityEn: "Houston",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "西雅图-America-Los-Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    cityZh: "西雅图",
    cityEn: "Seattle",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "波士顿-America-New-York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    cityZh: "波士顿",
    cityEn: "Boston",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "迈阿密-America-New-York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    cityZh: "迈阿密",
    cityEn: "Miami",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "拉斯维加斯-America-Los-Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    cityZh: "拉斯维加斯",
    cityEn: "Las Vegas",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "多伦多-America-Toronto",
    timezone: "America/Toronto",
    flag: "🇨🇦",
    cityZh: "多伦多",
    cityEn: "Toronto",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "温哥华-America-Vancouver",
    timezone: "America/Vancouver",
    flag: "🇨🇦",
    cityZh: "温哥华",
    cityEn: "Vancouver",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "蒙特利尔-America-Toronto",
    timezone: "America/Toronto",
    flag: "🇨🇦",
    cityZh: "蒙特利尔",
    cityEn: "Montreal",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "墨西哥城-America-Mexico-City",
    timezone: "America/Mexico_City",
    flag: "🇲🇽",
    cityZh: "墨西哥城",
    cityEn: "Mexico City",
    countryZh: "墨西哥",
    countryEn: "Mexico",
  },
  {
    id: "圣保罗-America-Sao-Paulo",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
    cityZh: "圣保罗",
    cityEn: "São Paulo",
    countryZh: "巴西",
    countryEn: "Brazil",
  },
  {
    id: "里约热内卢-America-Sao-Paulo",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
    cityZh: "里约热内卢",
    cityEn: "Rio de Janeiro",
    countryZh: "巴西",
    countryEn: "Brazil",
  },
  {
    id: "布宜诺斯艾利斯-America-Argentina-Buenos-Aires",
    timezone: "America/Argentina/Buenos_Aires",
    flag: "🇦🇷",
    cityZh: "布宜诺斯艾利斯",
    cityEn: "Buenos Aires",
    countryZh: "阿根廷",
    countryEn: "Argentina",
  },
  {
    id: "圣地亚哥-America-Santiago",
    timezone: "America/Santiago",
    flag: "🇨🇱",
    cityZh: "圣地亚哥",
    cityEn: "Santiago",
    countryZh: "智利",
    countryEn: "Chile",
  },
  {
    id: "利马-America-Lima",
    timezone: "America/Lima",
    flag: "🇵🇪",
    cityZh: "利马",
    cityEn: "Lima",
    countryZh: "秘鲁",
    countryEn: "Peru",
  },
  {
    id: "波哥大-America-Bogota",
    timezone: "America/Bogota",
    flag: "🇨🇴",
    cityZh: "波哥大",
    cityEn: "Bogotá",
    countryZh: "哥伦比亚",
    countryEn: "Colombia",
  },
  {
    id: "墨尔本-Australia-Melbourne",
    timezone: "Australia/Melbourne",
    flag: "🇦🇺",
    cityZh: "墨尔本",
    cityEn: "Melbourne",
    countryZh: "澳大利亚",
    countryEn: "Australia",
  },
  {
    id: "布里斯班-Australia-Brisbane",
    timezone: "Australia/Brisbane",
    flag: "🇦🇺",
    cityZh: "布里斯班",
    cityEn: "Brisbane",
    countryZh: "澳大利亚",
    countryEn: "Australia",
  },
  {
    id: "珀斯-Australia-Perth",
    timezone: "Australia/Perth",
    flag: "🇦🇺",
    cityZh: "珀斯",
    cityEn: "Perth",
    countryZh: "澳大利亚",
    countryEn: "Australia",
  },
  {
    id: "奥克兰-Pacific-Auckland",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
    cityZh: "奥克兰",
    cityEn: "Auckland",
    countryZh: "新西兰",
    countryEn: "New Zealand",
  },
  {
    id: "惠灵顿-Pacific-Auckland",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
    cityZh: "惠灵顿",
    cityEn: "Wellington",
    countryZh: "新西兰",
    countryEn: "New Zealand",
  },
  {
    id: "开罗-Africa-Cairo",
    timezone: "Africa/Cairo",
    flag: "🇪🇬",
    cityZh: "开罗",
    cityEn: "Cairo",
    countryZh: "埃及",
    countryEn: "Egypt",
  },
  {
    id: "约翰内斯堡-Africa-Johannesburg",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
    cityZh: "约翰内斯堡",
    cityEn: "Johannesburg",
    countryZh: "南非",
    countryEn: "South Africa",
  },
  {
    id: "开普敦-Africa-Johannesburg",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
    cityZh: "开普敦",
    cityEn: "Cape Town",
    countryZh: "南非",
    countryEn: "South Africa",
  },
  {
    id: "内罗毕-Africa-Nairobi",
    timezone: "Africa/Nairobi",
    flag: "🇰🇪",
    cityZh: "内罗毕",
    cityEn: "Nairobi",
    countryZh: "肯尼亚",
    countryEn: "Kenya",
  },
  {
    id: "拉各斯-Africa-Lagos",
    timezone: "Africa/Lagos",
    flag: "🇳🇬",
    cityZh: "拉各斯",
    cityEn: "Lagos",
    countryZh: "尼日利亚",
    countryEn: "Nigeria",
  },
  {
    id: "阿尔及尔-Africa-Algiers",
    timezone: "Africa/Algiers",
    flag: "🇩🇿",
    cityZh: "阿尔及尔",
    cityEn: "Algiers",
    countryZh: "阿尔及利亚",
    countryEn: "Algeria",
  },
  {
    id: "卡萨布兰卡-Africa-Casablanca",
    timezone: "Africa/Casablanca",
    flag: "🇲🇦",
    cityZh: "卡萨布兰卡",
    cityEn: "Casablanca",
    countryZh: "摩洛哥",
    countryEn: "Morocco",
  },
  {
    id: "突尼斯-Africa-Tunis",
    timezone: "Africa/Tunis",
    flag: "🇹🇳",
    cityZh: "突尼斯",
    cityEn: "Tunis",
    countryZh: "突尼斯",
    countryEn: "Tunisia",
  },
  {
    id: "阿克拉-Africa-Accra",
    timezone: "Africa/Accra",
    flag: "🇬🇭",
    cityZh: "阿克拉",
    cityEn: "Accra",
    countryZh: "加纳",
    countryEn: "Ghana",
  },
  {
    id: "达喀尔-Africa-Dakar",
    timezone: "Africa/Dakar",
    flag: "🇸🇳",
    cityZh: "达喀尔",
    cityEn: "Dakar",
    countryZh: "塞内加尔",
    countryEn: "Senegal",
  },
  {
    id: "亚的斯亚贝巴-Africa-Addis-Ababa",
    timezone: "Africa/Addis_Ababa",
    flag: "🇪🇹",
    cityZh: "亚的斯亚贝巴",
    cityEn: "Addis Ababa",
    countryZh: "埃塞俄比亚",
    countryEn: "Ethiopia",
  },
  {
    id: "金沙萨-Africa-Kinshasa",
    timezone: "Africa/Kinshasa",
    flag: "🇨🇩",
    cityZh: "金沙萨",
    cityEn: "Kinshasa",
    countryZh: "刚果（金）",
    countryEn: "DR Congo",
  },
  {
    id: "卢萨卡-Africa-Lusaka",
    timezone: "Africa/Lusaka",
    flag: "🇿🇲",
    cityZh: "卢萨卡",
    cityEn: "Lusaka",
    countryZh: "赞比亚",
    countryEn: "Zambia",
  },
  {
    id: "哈拉雷-Africa-Harare",
    timezone: "Africa/Harare",
    flag: "🇿🇼",
    cityZh: "哈拉雷",
    cityEn: "Harare",
    countryZh: "津巴布韦",
    countryEn: "Zimbabwe",
  },
  {
    id: "坎帕拉-Africa-Kampala",
    timezone: "Africa/Kampala",
    flag: "🇺🇬",
    cityZh: "坎帕拉",
    cityEn: "Kampala",
    countryZh: "乌干达",
    countryEn: "Uganda",
  },
  {
    id: "达累斯萨拉姆-Africa-Dar-es-Salaam",
    timezone: "Africa/Dar_es_Salaam",
    flag: "🇹🇿",
    cityZh: "达累斯萨拉姆",
    cityEn: "Dar es Salaam",
    countryZh: "坦桑尼亚",
    countryEn: "Tanzania",
  },
  {
    id: "的黎波里-Africa-Tripoli",
    timezone: "Africa/Tripoli",
    flag: "🇱🇾",
    cityZh: "的黎波里",
    cityEn: "Tripoli",
    countryZh: "利比亚",
    countryEn: "Libya",
  },
  {
    id: "喀土穆-Africa-Khartoum",
    timezone: "Africa/Khartoum",
    flag: "🇸🇩",
    cityZh: "喀土穆",
    cityEn: "Khartoum",
    countryZh: "苏丹",
    countryEn: "Sudan",
  },
  {
    id: "阿比让-Africa-Abidjan",
    timezone: "Africa/Abidjan",
    flag: "🇨🇮",
    cityZh: "阿比让",
    cityEn: "Abidjan",
    countryZh: "科特迪瓦",
    countryEn: "Côte d'Ivoire",
  },
  {
    id: "仰光-Asia-Yangon",
    timezone: "Asia/Yangon",
    flag: "🇲🇲",
    cityZh: "仰光",
    cityEn: "Yangon",
    countryZh: "缅甸",
    countryEn: "Myanmar",
  },
  {
    id: "科伦坡-Asia-Colombo",
    timezone: "Asia/Colombo",
    flag: "🇱🇰",
    cityZh: "科伦坡",
    cityEn: "Colombo",
    countryZh: "斯里兰卡",
    countryEn: "Sri Lanka",
  },
  {
    id: "喀布尔-Asia-Kabul",
    timezone: "Asia/Kabul",
    flag: "🇦🇫",
    cityZh: "喀布尔",
    cityEn: "Kabul",
    countryZh: "阿富汗",
    countryEn: "Afghanistan",
  },
  {
    id: "塔什干-Asia-Tashkent",
    timezone: "Asia/Tashkent",
    flag: "🇺🇿",
    cityZh: "塔什干",
    cityEn: "Tashkent",
    countryZh: "乌兹别克斯坦",
    countryEn: "Uzbekistan",
  },
  {
    id: "阿拉木图-Asia-Almaty",
    timezone: "Asia/Almaty",
    flag: "🇰🇿",
    cityZh: "阿拉木图",
    cityEn: "Almaty",
    countryZh: "哈萨克斯坦",
    countryEn: "Kazakhstan",
  },
  {
    id: "比什凯克-Asia-Bishkek",
    timezone: "Asia/Bishkek",
    flag: "🇰🇬",
    cityZh: "比什凯克",
    cityEn: "Bishkek",
    countryZh: "吉尔吉斯斯坦",
    countryEn: "Kyrgyzstan",
  },
  {
    id: "杜尚别-Asia-Dushanbe",
    timezone: "Asia/Dushanbe",
    flag: "🇹🇯",
    cityZh: "杜尚别",
    cityEn: "Dushanbe",
    countryZh: "塔吉克斯坦",
    countryEn: "Tajikistan",
  },
  {
    id: "阿什哈巴德-Asia-Ashgabat",
    timezone: "Asia/Ashgabat",
    flag: "🇹🇲",
    cityZh: "阿什哈巴德",
    cityEn: "Ashgabat",
    countryZh: "土库曼斯坦",
    countryEn: "Turkmenistan",
  },
  {
    id: "巴库-Asia-Baku",
    timezone: "Asia/Baku",
    flag: "🇦🇿",
    cityZh: "巴库",
    cityEn: "Baku",
    countryZh: "阿塞拜疆",
    countryEn: "Azerbaijan",
  },
  {
    id: "埃里温-Asia-Yerevan",
    timezone: "Asia/Yerevan",
    flag: "🇦🇲",
    cityZh: "埃里温",
    cityEn: "Yerevan",
    countryZh: "亚美尼亚",
    countryEn: "Armenia",
  },
  {
    id: "第比利斯-Asia-Tbilisi",
    timezone: "Asia/Tbilisi",
    flag: "🇬🇪",
    cityZh: "第比利斯",
    cityEn: "Tbilisi",
    countryZh: "格鲁吉亚",
    countryEn: "Georgia",
  },
  {
    id: "贝鲁特-Asia-Beirut",
    timezone: "Asia/Beirut",
    flag: "🇱🇧",
    cityZh: "贝鲁特",
    cityEn: "Beirut",
    countryZh: "黎巴嫩",
    countryEn: "Lebanon",
  },
  {
    id: "大马士革-Asia-Damascus",
    timezone: "Asia/Damascus",
    flag: "🇸🇾",
    cityZh: "大马士革",
    cityEn: "Damascus",
    countryZh: "叙利亚",
    countryEn: "Syria",
  },
  {
    id: "安曼-Asia-Amman",
    timezone: "Asia/Amman",
    flag: "🇯🇴",
    cityZh: "安曼",
    cityEn: "Amman",
    countryZh: "约旦",
    countryEn: "Jordan",
  },
  {
    id: "巴格达-Asia-Baghdad",
    timezone: "Asia/Baghdad",
    flag: "🇮🇶",
    cityZh: "巴格达",
    cityEn: "Baghdad",
    countryZh: "伊拉克",
    countryEn: "Iraq",
  },
  {
    id: "科威特城-Asia-Kuwait",
    timezone: "Asia/Kuwait",
    flag: "🇰🇼",
    cityZh: "科威特城",
    cityEn: "Kuwait City",
    countryZh: "科威特",
    countryEn: "Kuwait",
  },
  {
    id: "马斯喀特-Asia-Muscat",
    timezone: "Asia/Muscat",
    flag: "🇴🇲",
    cityZh: "马斯喀特",
    cityEn: "Muscat",
    countryZh: "阿曼",
    countryEn: "Oman",
  },
  {
    id: "麦纳麦-Asia-Bahrain",
    timezone: "Asia/Bahrain",
    flag: "🇧🇭",
    cityZh: "麦纳麦",
    cityEn: "Manama",
    countryZh: "巴林",
    countryEn: "Bahrain",
  },
  {
    id: "萨那-Asia-Aden",
    timezone: "Asia/Aden",
    flag: "🇾🇪",
    cityZh: "萨那",
    cityEn: "Sana'a",
    countryZh: "也门",
    countryEn: "Yemen",
  },
  {
    id: "金边-Asia-Phnom-Penh",
    timezone: "Asia/Phnom_Penh",
    flag: "🇰🇭",
    cityZh: "金边",
    cityEn: "Phnom Penh",
    countryZh: "柬埔寨",
    countryEn: "Cambodia",
  },
  {
    id: "万象-Asia-Vientiane",
    timezone: "Asia/Vientiane",
    flag: "🇱🇦",
    cityZh: "万象",
    cityEn: "Vientiane",
    countryZh: "老挝",
    countryEn: "Laos",
  },
  {
    id: "乌兰巴托-Asia-Ulaanbaatar",
    timezone: "Asia/Ulaanbaatar",
    flag: "🇲🇳",
    cityZh: "乌兰巴托",
    cityEn: "Ulaanbaatar",
    countryZh: "蒙古",
    countryEn: "Mongolia",
  },
  {
    id: "平壤-Asia-Pyongyang",
    timezone: "Asia/Pyongyang",
    flag: "🇰🇵",
    cityZh: "平壤",
    cityEn: "Pyongyang",
    countryZh: "朝鲜",
    countryEn: "North Korea",
  },
  {
    id: "斯里巴加湾-Asia-Brunei",
    timezone: "Asia/Brunei",
    flag: "🇧🇳",
    cityZh: "斯里巴加湾",
    cityEn: "Bandar Seri Begawan",
    countryZh: "文莱",
    countryEn: "Brunei",
  },
  {
    id: "帝力-Asia-Dili",
    timezone: "Asia/Dili",
    flag: "🇹🇱",
    cityZh: "帝力",
    cityEn: "Dili",
    countryZh: "东帝汶",
    countryEn: "Timor-Leste",
  },
  {
    id: "马累-Indian-Maldives",
    timezone: "Indian/Maldives",
    flag: "🇲🇻",
    cityZh: "马累",
    cityEn: "Malé",
    countryZh: "马尔代夫",
    countryEn: "Maldives",
  },
  {
    id: "廷布-Asia-Thimphu",
    timezone: "Asia/Thimphu",
    flag: "🇧🇹",
    cityZh: "廷布",
    cityEn: "Thimphu",
    countryZh: "不丹",
    countryEn: "Bhutan",
  },
  {
    id: "基辅-Europe-Kiev",
    timezone: "Europe/Kiev",
    flag: "🇺🇦",
    cityZh: "基辅",
    cityEn: "Kyiv",
    countryZh: "乌克兰",
    countryEn: "Ukraine",
  },
  {
    id: "明斯克-Europe-Minsk",
    timezone: "Europe/Minsk",
    flag: "🇧🇾",
    cityZh: "明斯克",
    cityEn: "Minsk",
    countryZh: "白俄罗斯",
    countryEn: "Belarus",
  },
  {
    id: "布加勒斯特-Europe-Bucharest",
    timezone: "Europe/Bucharest",
    flag: "🇷🇴",
    cityZh: "布加勒斯特",
    cityEn: "Bucharest",
    countryZh: "罗马尼亚",
    countryEn: "Romania",
  },
  {
    id: "索菲亚-Europe-Sofia",
    timezone: "Europe/Sofia",
    flag: "🇧🇬",
    cityZh: "索菲亚",
    cityEn: "Sofia",
    countryZh: "保加利亚",
    countryEn: "Bulgaria",
  },
  {
    id: "贝尔格莱德-Europe-Belgrade",
    timezone: "Europe/Belgrade",
    flag: "🇷🇸",
    cityZh: "贝尔格莱德",
    cityEn: "Belgrade",
    countryZh: "塞尔维亚",
    countryEn: "Serbia",
  },
  {
    id: "萨格勒布-Europe-Zagreb",
    timezone: "Europe/Zagreb",
    flag: "🇭🇷",
    cityZh: "萨格勒布",
    cityEn: "Zagreb",
    countryZh: "克罗地亚",
    countryEn: "Croatia",
  },
  {
    id: "卢布尔雅那-Europe-Ljubljana",
    timezone: "Europe/Ljubljana",
    flag: "🇸🇮",
    cityZh: "卢布尔雅那",
    cityEn: "Ljubljana",
    countryZh: "斯洛文尼亚",
    countryEn: "Slovenia",
  },
  {
    id: "萨拉热窝-Europe-Sarajevo",
    timezone: "Europe/Sarajevo",
    flag: "🇧🇦",
    cityZh: "萨拉热窝",
    cityEn: "Sarajevo",
    countryZh: "波黑",
    countryEn: "Bosnia and Herzegovina",
  },
  {
    id: "斯科普里-Europe-Skopje",
    timezone: "Europe/Skopje",
    flag: "🇲🇰",
    cityZh: "斯科普里",
    cityEn: "Skopje",
    countryZh: "北马其顿",
    countryEn: "North Macedonia",
  },
  {
    id: "地拉那-Europe-Tirane",
    timezone: "Europe/Tirane",
    flag: "🇦🇱",
    cityZh: "地拉那",
    cityEn: "Tirana",
    countryZh: "阿尔巴尼亚",
    countryEn: "Albania",
  },
  {
    id: "塔林-Europe-Tallinn",
    timezone: "Europe/Tallinn",
    flag: "🇪🇪",
    cityZh: "塔林",
    cityEn: "Tallinn",
    countryZh: "爱沙尼亚",
    countryEn: "Estonia",
  },
  {
    id: "里加-Europe-Riga",
    timezone: "Europe/Riga",
    flag: "🇱🇻",
    cityZh: "里加",
    cityEn: "Riga",
    countryZh: "拉脱维亚",
    countryEn: "Latvia",
  },
  {
    id: "维尔纽斯-Europe-Vilnius",
    timezone: "Europe/Vilnius",
    flag: "🇱🇹",
    cityZh: "维尔纽斯",
    cityEn: "Vilnius",
    countryZh: "立陶宛",
    countryEn: "Lithuania",
  },
  {
    id: "雷克雅未克-Atlantic-Reykjavik",
    timezone: "Atlantic/Reykjavik",
    flag: "🇮🇸",
    cityZh: "雷克雅未克",
    cityEn: "Reykjavik",
    countryZh: "冰岛",
    countryEn: "Iceland",
  },
  {
    id: "卢森堡-Europe-Luxembourg",
    timezone: "Europe/Luxembourg",
    flag: "🇱🇺",
    cityZh: "卢森堡",
    cityEn: "Luxembourg",
    countryZh: "卢森堡",
    countryEn: "Luxembourg",
  },
  {
    id: "摩纳哥-Europe-Monaco",
    timezone: "Europe/Monaco",
    flag: "🇲🇨",
    cityZh: "摩纳哥",
    cityEn: "Monaco",
    countryZh: "摩纳哥",
    countryEn: "Monaco",
  },
  {
    id: "安道尔-Europe-Andorra",
    timezone: "Europe/Andorra",
    flag: "🇦🇩",
    cityZh: "安道尔",
    cityEn: "Andorra",
    countryZh: "安道尔",
    countryEn: "Andorra",
  },
  {
    id: "马耳他-Europe-Malta",
    timezone: "Europe/Malta",
    flag: "🇲🇹",
    cityZh: "马耳他",
    cityEn: "Malta",
    countryZh: "马耳他",
    countryEn: "Malta",
  },
  {
    id: "尼科西亚-Asia-Nicosia",
    timezone: "Asia/Nicosia",
    flag: "🇨🇾",
    cityZh: "尼科西亚",
    cityEn: "Nicosia",
    countryZh: "塞浦路斯",
    countryEn: "Cyprus",
  },
  {
    id: "丹佛-America-Denver",
    timezone: "America/Denver",
    flag: "🇺🇸",
    cityZh: "丹佛",
    cityEn: "Denver",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "凤凰城-America-Phoenix",
    timezone: "America/Phoenix",
    flag: "🇺🇸",
    cityZh: "凤凰城",
    cityEn: "Phoenix",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "费城-America-New-York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    cityZh: "费城",
    cityEn: "Philadelphia",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "达拉斯-America-Chicago",
    timezone: "America/Chicago",
    flag: "🇺🇸",
    cityZh: "达拉斯",
    cityEn: "Dallas",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "圣迭戈-America-Los-Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    cityZh: "圣迭戈",
    cityEn: "San Diego",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "檀香山-Pacific-Honolulu",
    timezone: "Pacific/Honolulu",
    flag: "🇺🇸",
    cityZh: "檀香山",
    cityEn: "Honolulu",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "安克雷奇-America-Anchorage",
    timezone: "America/Anchorage",
    flag: "🇺🇸",
    cityZh: "安克雷奇",
    cityEn: "Anchorage",
    countryZh: "美国",
    countryEn: "United States",
  },
  {
    id: "渥太华-America-Toronto",
    timezone: "America/Toronto",
    flag: "🇨🇦",
    cityZh: "渥太华",
    cityEn: "Ottawa",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "卡尔加里-America-Edmonton",
    timezone: "America/Edmonton",
    flag: "🇨🇦",
    cityZh: "卡尔加里",
    cityEn: "Calgary",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "哈利法克斯-America-Halifax",
    timezone: "America/Halifax",
    flag: "🇨🇦",
    cityZh: "哈利法克斯",
    cityEn: "Halifax",
    countryZh: "加拿大",
    countryEn: "Canada",
  },
  {
    id: "哈瓦那-America-Havana",
    timezone: "America/Havana",
    flag: "🇨🇺",
    cityZh: "哈瓦那",
    cityEn: "Havana",
    countryZh: "古巴",
    countryEn: "Cuba",
  },
  {
    id: "圣多明各-America-Santo-Domingo",
    timezone: "America/Santo_Domingo",
    flag: "🇩🇴",
    cityZh: "圣多明各",
    cityEn: "Santo Domingo",
    countryZh: "多米尼加",
    countryEn: "Dominican Republic",
  },
  {
    id: "太子港-America-Port-au-Prince",
    timezone: "America/Port-au-Prince",
    flag: "🇭🇹",
    cityZh: "太子港",
    cityEn: "Port-au-Prince",
    countryZh: "海地",
    countryEn: "Haiti",
  },
  {
    id: "金斯敦-America-Jamaica",
    timezone: "America/Jamaica",
    flag: "🇯🇲",
    cityZh: "金斯敦",
    cityEn: "Kingston",
    countryZh: "牙买加",
    countryEn: "Jamaica",
  },
  {
    id: "巴拿马城-America-Panama",
    timezone: "America/Panama",
    flag: "🇵🇦",
    cityZh: "巴拿马城",
    cityEn: "Panama City",
    countryZh: "巴拿马",
    countryEn: "Panama",
  },
  {
    id: "圣何塞-America-Costa-Rica",
    timezone: "America/Costa_Rica",
    flag: "🇨🇷",
    cityZh: "圣何塞",
    cityEn: "San José",
    countryZh: "哥斯达黎加",
    countryEn: "Costa Rica",
  },
  {
    id: "危地马拉城-America-Guatemala",
    timezone: "America/Guatemala",
    flag: "🇬🇹",
    cityZh: "危地马拉城",
    cityEn: "Guatemala City",
    countryZh: "危地马拉",
    countryEn: "Guatemala",
  },
  {
    id: "特古西加尔巴-America-Tegucigalpa",
    timezone: "America/Tegucigalpa",
    flag: "🇭🇳",
    cityZh: "特古西加尔巴",
    cityEn: "Tegucigalpa",
    countryZh: "洪都拉斯",
    countryEn: "Honduras",
  },
  {
    id: "马那瓜-America-Managua",
    timezone: "America/Managua",
    flag: "🇳🇮",
    cityZh: "马那瓜",
    cityEn: "Managua",
    countryZh: "尼加拉瓜",
    countryEn: "Nicaragua",
  },
  {
    id: "圣萨尔瓦多-America-El-Salvador",
    timezone: "America/El_Salvador",
    flag: "🇸🇻",
    cityZh: "圣萨尔瓦多",
    cityEn: "San Salvador",
    countryZh: "萨尔瓦多",
    countryEn: "El Salvador",
  },
  {
    id: "加拉加斯-America-Caracas",
    timezone: "America/Caracas",
    flag: "🇻🇪",
    cityZh: "加拉加斯",
    cityEn: "Caracas",
    countryZh: "委内瑞拉",
    countryEn: "Venezuela",
  },
  {
    id: "基多-America-Guayaquil",
    timezone: "America/Guayaquil",
    flag: "🇪🇨",
    cityZh: "基多",
    cityEn: "Quito",
    countryZh: "厄瓜多尔",
    countryEn: "Ecuador",
  },
  {
    id: "拉巴斯-America-La-Paz",
    timezone: "America/La_Paz",
    flag: "🇧🇴",
    cityZh: "拉巴斯",
    cityEn: "La Paz",
    countryZh: "玻利维亚",
    countryEn: "Bolivia",
  },
  {
    id: "亚松森-America-Asuncion",
    timezone: "America/Asuncion",
    flag: "🇵🇾",
    cityZh: "亚松森",
    cityEn: "Asunción",
    countryZh: "巴拉圭",
    countryEn: "Paraguay",
  },
  {
    id: "蒙得维的亚-America-Montevideo",
    timezone: "America/Montevideo",
    flag: "🇺🇾",
    cityZh: "蒙得维的亚",
    cityEn: "Montevideo",
    countryZh: "乌拉圭",
    countryEn: "Uruguay",
  },
  {
    id: "苏瓦-Pacific-Fiji",
    timezone: "Pacific/Fiji",
    flag: "🇫🇯",
    cityZh: "苏瓦",
    cityEn: "Suva",
    countryZh: "斐济",
    countryEn: "Fiji",
  },
  {
    id: "努美阿-Pacific-Noumea",
    timezone: "Pacific/Noumea",
    flag: "🇳🇨",
    cityZh: "努美阿",
    cityEn: "Nouméa",
    countryZh: "新喀里多尼亚",
    countryEn: "New Caledonia",
  },
  {
    id: "塔希提-Pacific-Tahiti",
    timezone: "Pacific/Tahiti",
    flag: "🇵🇫",
    cityZh: "塔希提",
    cityEn: "Tahiti",
    countryZh: "法属波利尼西亚",
    countryEn: "French Polynesia",
  },
  {
    id: "阿皮亚-Pacific-Apia",
    timezone: "Pacific/Apia",
    flag: "🇼🇸",
    cityZh: "阿皮亚",
    cityEn: "Apia",
    countryZh: "萨摩亚",
    countryEn: "Samoa",
  },
  {
    id: "努库阿洛法-Pacific-Tongatapu",
    timezone: "Pacific/Tongatapu",
    flag: "🇹🇴",
    cityZh: "努库阿洛法",
    cityEn: "Nuku'alofa",
    countryZh: "汤加",
    countryEn: "Tonga",
  },
  {
    id: "维拉港-Pacific-Efate",
    timezone: "Pacific/Efate",
    flag: "🇻🇺",
    cityZh: "维拉港",
    cityEn: "Port Vila",
    countryZh: "瓦努阿图",
    countryEn: "Vanuatu",
  },
  {
    id: "莫尔兹比港-Pacific-Port-Moresby",
    timezone: "Pacific/Port_Moresby",
    flag: "🇵🇬",
    cityZh: "莫尔兹比港",
    cityEn: "Port Moresby",
    countryZh: "巴布亚新几内亚",
    countryEn: "Papua New Guinea",
  },
  {
    id: "霍尼亚拉-Pacific-Guadalcanal",
    timezone: "Pacific/Guadalcanal",
    flag: "🇸🇧",
    cityZh: "霍尼亚拉",
    cityEn: "Honiara",
    countryZh: "所罗门群岛",
    countryEn: "Solomon Islands",
  },
  {
    id: "帕利基尔-Pacific-Pohnpei",
    timezone: "Pacific/Pohnpei",
    flag: "🇫🇲",
    cityZh: "帕利基尔",
    cityEn: "Palikir",
    countryZh: "密克罗尼西亚",
    countryEn: "Micronesia",
  },
  {
    id: "马朱罗-Pacific-Majuro",
    timezone: "Pacific/Majuro",
    flag: "🇲🇭",
    cityZh: "马朱罗",
    cityEn: "Majuro",
    countryZh: "马绍尔群岛",
    countryEn: "Marshall Islands",
  },
  {
    id: "塔拉瓦-Pacific-Tarawa",
    timezone: "Pacific/Tarawa",
    flag: "🇰🇮",
    cityZh: "塔拉瓦",
    cityEn: "Tarawa",
    countryZh: "基里巴斯",
    countryEn: "Kiribati",
  },
  {
    id: "富纳富提-Pacific-Funafuti",
    timezone: "Pacific/Funafuti",
    flag: "🇹🇻",
    cityZh: "富纳富提",
    cityEn: "Funafuti",
    countryZh: "图瓦卢",
    countryEn: "Tuvalu",
  },
  {
    id: "亚伦-Pacific-Nauru",
    timezone: "Pacific/Nauru",
    flag: "🇳🇷",
    cityZh: "亚伦",
    cityEn: "Yaren",
    countryZh: "瑙鲁",
    countryEn: "Nauru",
  },
  {
    id: "科罗尔-Pacific-Palau",
    timezone: "Pacific/Palau",
    flag: "🇵🇼",
    cityZh: "科罗尔",
    cityEn: "Koror",
    countryZh: "帕劳",
    countryEn: "Palau",
  },
]

export const FEATURED_CITIES = WORLD_CITIES.filter((c) => c.featured)
